services:
    tha-backend:
        build:
            context: .
            dockerfile: Dockerfile.fastapi
        ports:
            - '8000:8000'
        networks:
            - talent-hunter-network

    tha-frontend:
        build:
            context: .
            dockerfile: Dockerfile.streamlit
        ports:
            - '8501:8501'
        depends_on:
            - tha-backend
        networks:
            - talent-hunter-network

    qdrant:
        image: qdrant/qdrant:latest
        container_name: tha-qdrant
        ports:
            - '6333:6333' # REST API
            - '6334:6334' # gRPC API
        volumes:
            - qdrant_storage:/qdrant/storage
        environment:
            - QDRANT__SERVICE__HTTP_PORT=6333
            - QDRANT__SERVICE__GRPC_PORT=6334
        networks:
            - talent-hunter-network

networks:
    talent-hunter-network:
        driver: bridge

volumes:
    qdrant_storage:
        driver: local
