FROM python:3.11-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app
WORKDIR /app

# Install dependencies
RUN uv sync --frozen --no-cache

EXPOSE 8501

CMD ["/app/.venv/bin/streamlit", "run", "frontend/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
