apiVersion: v1
kind: Service
metadata:
    name: talent-hunter-agent-service
spec:
    type: LoadBalancer
    selector:
        app: talent-hunter-agent
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
